/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jo.just.charts;

import org.jfree.chart.ChartPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//jo.just.charts//TimeSeriesChart//EN",
autostore = false)
@TopComponent.Description(preferredID = "TimeSeriesChartTopComponent",
iconBase = "jo/just/charts/resources/chart16.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "jo.just.charts.TimeSeriesChartTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_TimeSeriesChartAction",
preferredID = "TimeSeriesChartTopComponent")
public final class TimeSeriesChartTopComponent extends TopComponent {

    public TimeSeriesChartTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TimeSeriesChartTopComponent.class, "CTL_TimeSeriesChartTopComponent"));
        setToolTipText(NbBundle.getMessage(TimeSeriesChartTopComponent.class, "HINT_TimeSeriesChartTopComponent"));

//        TimeSeriesChartDemo1 demo = new TimeSeriesChartDemo1("Hosts Utilization");
//        demo.revalidate();
//        demo.setVisible(true);
//        jScrollPane1.setViewportView(demo);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        jScrollPane1.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        TimeSeriesChartDemo1 demo = new TimeSeriesChartDemo1("<< Hosts Utilization >>"+System.currentTimeMillis());
        ChartPanel chartPanel = demo.getChartPanel();
        chartPanel.revalidate();
        chartPanel.setVisible(true);
        jScrollPane1.setViewportView(chartPanel);
//        System.err.println("componentOpened()");
    }

    @Override
    public void componentClosed() {
//        System.err.println("componentClosed()");
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
